Repository Team-CrazyDiamond/SeatAssist, pull requests merged in 2021-10, with the labels that each got.

#19 スタート画面の作成
  main/app/src/main/java/com/example/seatassist/ui/start/StartScreen.kt
  main/app/src/main/res/drawable-180dpi/chair_backcolor_yellow_hhd.png
Labels: plottype

#20 プロトタイプ
  .idea/workspace.xml
  main/.idea/.name
  main/app/build.gradle
  main/app/src/main/java/com/example/seatassist/MainActivity.kt
  main/app/src/main/java/com/example/seatassist/data/SeatAssistData.kt
  main/app/src/main/java/com/example/seatassist/ui/components/CommonUi.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainViewModel.kt
  main/app/src/main/java/com/example/seatassist/ui/members/MembersScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/size/SizeScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/start/StartScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/theme/Color.kt
  main/app/src/main/java/com/example/seatassist/ui/theme/Theme.kt
  main/app/src/main/res/drawable-180dpi/chair_backcolor_yellow_hhd.png
  main/build.gradle
Labels: plottype

#21 起動画面の変更
  main/app/src/main/java/com/example/seatassist/MainActivity.kt
  main/app/src/main/java/com/example/seatassist/SeatAssistScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/start/StartScreen.kt
Labels: feature

#29 ステータスバー，ナビゲーションバーの色変更
  main/app/build.gradle
  main/app/src/main/java/com/example/seatassist/MainActivity.kt
Labels: UI

#35 Custom/all
  main/app/build.gradle
  main/app/src/main/java/com/example/seatassist/MainActivity.kt
  main/app/src/main/java/com/example/seatassist/ui/components/CommonUi.kt
  main/app/src/main/java/com/example/seatassist/ui/custom/CustomScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainViewModel.kt
Labels: bug, feature

#40 使い方ページの雛形作成，オブジェクトカラーの変更
  main/app/src/main/java/com/example/seatassist/data/SeatAssistData.kt
  main/app/src/main/java/com/example/seatassist/ui/custom/CustomScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/usage/UsageScreen.kt
  main/app/src/main/res/drawable/usage_1.png
Labels: feature, UI

#43 Lottery/base
  main/app/src/main/java/com/example/seatassist/MainActivity.kt
  main/app/src/main/java/com/example/seatassist/SeatAssistScreen.kt
  main/app/src/main/java/com/example/seatassist/data/SeatAssistData.kt
  main/app/src/main/java/com/example/seatassist/ui/components/CommonUi.kt
  main/app/src/main/java/com/example/seatassist/ui/lottery/LotteryScreen.kt.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainViewModel.kt
Labels: feature, UI

#45 Members/make number of members screen
  main/app/src/main/java/com/example/seatassist/MainActivity.kt
  main/app/src/main/java/com/example/seatassist/SeatAssistScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/components/CommonUi.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainViewModel.kt
  main/app/src/main/java/com/example/seatassist/ui/members/MembersScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/members/NumberScreen.kt
Labels: bug, feature, UI
