Repository Team-CrazyDiamond/SeatAssist, pull requests merged in 2021-11, with the labels that each got.

#66 All/animation
  main/app/build.gradle
  main/app/src/main/java/com/example/seatassist/MainActivity.kt
  main/app/src/main/java/com/example/seatassist/ui/components/CommonUi.kt
  main/app/src/main/java/com/example/seatassist/ui/custom/CustomScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/lottery/LotteryScreen.kt.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/members/MembersScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/members/NumberScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/splash/SplashScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/start/StartScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/theme/Color.kt
  main/app/src/main/java/com/example/seatassist/ui/usage/UsageScreen.kt
Labels: UI

#69 All/object control mac
  main/app/src/main/java/com/example/seatassist/MainActivity.kt
  main/app/src/main/java/com/example/seatassist/ui/lottery/LotteryScreen.kt.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainScreen.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainViewModel.kt
  main/app/src/main/java/com/example/seatassist/ui/main/MainViewModelFactory.kt
  main/app/src/main/java/com/example/seatassist/ui/number/NunmberScreen.kt
Labels: bug, UI

#70 使い方カードの追加
  main/app/src/main/java/com/example/seatassist/ui/usage/UsageScreen.kt
  main/app/src/main/res/drawable-180dpi/custom_screen.jpg
  main/app/src/main/res/drawable-180dpi/lottery_screen.jpg
  main/app/src/main/res/drawable-180dpi/main_screen.jpg
  main/app/src/main/res/drawable-180dpi/member_screen.jpg
  main/app/src/main/res/drawable-180dpi/number_screen.jpg
Labels: UI

#71 タップした位置に,オブジェクトの中心が来るように調整
  main/app/src/main/java/com/example/seatassist/ui/main/MainViewModel.kt
Labels: bug

#72 画面を縦方向に固定
  main/app/src/main/AndroidManifest.xml
Labels: feature

#73 スタート画面のアニメーションサイズを変更
  main/app/src/main/java/com/example/seatassist/MainActivity.kt
  main/app/src/main/java/com/example/seatassist/ui/lottery/LotteryScreen.kt.kt
  main/app/src/main/java/com/example/seatassist/ui/start/StartScreen.kt
Labels: bug, UI
